# Common functionality to all TouchOSC controls

string tabpage          # Control tabpage
string name             # Control Name
int16 x                 # X position of the control
int16 y                 # Y position of the control
uint16 width            # Width of the control
uint16 height           # Height of the control
bool visibility         # Visibility of the control

# Possible colors are:
# "red", "green", "blue", "yellow", "orange", "purple", "gray"
string color            # Color of the control
