#!/usr/bin/env python

import roslib; roslib.load_manifest('osc_bridge')
import rospy

from oscbridge import OSCBridge

if __name__=="__main__":
    rospy.init_node("osc_bridge")
    rospy.loginfo("ROS OSC Python Node")
    
    bridge = OSCBridge("asdf",12345)

    while True:
        if rospy.is_shutdown():
            bridge.stop()
            break
        bridge.run()

